# Generated by Django 6.0.7 on 2026-07-31 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee_id'], name='accounts_em_employe_51b309_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['status'], name='accounts_em_status_5214cc_idx'),
        ),
    ]
